/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as LoginRouteImport } from './routes/login'
import { Route as R403RouteImport } from './routes/403'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LaporanIndexRouteImport } from './routes/laporan/index'
import { Route as JadwalIndexRouteImport } from './routes/jadwal/index'
import { Route as DisplayIndexRouteImport } from './routes/display/index'
import { Route as CekAntreanIndexRouteImport } from './routes/cek-antrean/index'
import { Route as PerawatAntreanRouteImport } from './routes/perawat/antrean'
import { Route as PerawatAsistenAntreanRouteImport } from './routes/perawat-asisten/antrean'
import { Route as PengaturanTemplatePesanRouteImport } from './routes/pengaturan/template-pesan'
import { Route as PengaturanKonfigurasiWhatsappRouteImport } from './routes/pengaturan/konfigurasi-whatsapp'
import { Route as PengaturanKonfigurasiSistemRouteImport } from './routes/pengaturan/konfigurasi-sistem'
import { Route as PengaturanKonfigurasiPengingatRouteImport } from './routes/pengaturan/konfigurasi-pengingat'
import { Route as PengaturanJadwalKontrolRouteImport } from './routes/pengaturan/jadwal-kontrol'
import { Route as PengaturanFaqRouteImport } from './routes/pengaturan/faq'
import { Route as MasterUsersRouteImport } from './routes/master/users'
import { Route as MasterRolesRouteImport } from './routes/master/roles'
import { Route as MasterPoliRouteImport } from './routes/master/poli'
import { Route as MasterPasienRouteImport } from './routes/master/pasien'
import { Route as DokterAntreanRouteImport } from './routes/dokter/antrean'
import { Route as AdministrasiAntreanRouteImport } from './routes/administrasi/antrean'

const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanIndexRoute = LaporanIndexRouteImport.update({
  id: '/laporan/',
  path: '/laporan/',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalIndexRoute = JadwalIndexRouteImport.update({
  id: '/jadwal/',
  path: '/jadwal/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayIndexRoute = DisplayIndexRouteImport.update({
  id: '/display/',
  path: '/display/',
  getParentRoute: () => rootRouteImport,
} as any)
const CekAntreanIndexRoute = CekAntreanIndexRouteImport.update({
  id: '/cek-antrean/',
  path: '/cek-antrean/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerawatAntreanRoute = PerawatAntreanRouteImport.update({
  id: '/perawat/antrean',
  path: '/perawat/antrean',
  getParentRoute: () => rootRouteImport,
} as any)
const PerawatAsistenAntreanRoute = PerawatAsistenAntreanRouteImport.update({
  id: '/perawat-asisten/antrean',
  path: '/perawat-asisten/antrean',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanTemplatePesanRoute = PengaturanTemplatePesanRouteImport.update({
  id: '/pengaturan/template-pesan',
  path: '/pengaturan/template-pesan',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanKonfigurasiWhatsappRoute =
  PengaturanKonfigurasiWhatsappRouteImport.update({
    id: '/pengaturan/konfigurasi-whatsapp',
    path: '/pengaturan/konfigurasi-whatsapp',
    getParentRoute: () => rootRouteImport,
  } as any)
const PengaturanKonfigurasiSistemRoute =
  PengaturanKonfigurasiSistemRouteImport.update({
    id: '/pengaturan/konfigurasi-sistem',
    path: '/pengaturan/konfigurasi-sistem',
    getParentRoute: () => rootRouteImport,
  } as any)
const PengaturanKonfigurasiPengingatRoute =
  PengaturanKonfigurasiPengingatRouteImport.update({
    id: '/pengaturan/konfigurasi-pengingat',
    path: '/pengaturan/konfigurasi-pengingat',
    getParentRoute: () => rootRouteImport,
  } as any)
const PengaturanJadwalKontrolRoute = PengaturanJadwalKontrolRouteImport.update({
  id: '/pengaturan/jadwal-kontrol',
  path: '/pengaturan/jadwal-kontrol',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanFaqRoute = PengaturanFaqRouteImport.update({
  id: '/pengaturan/faq',
  path: '/pengaturan/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterUsersRoute = MasterUsersRouteImport.update({
  id: '/master/users',
  path: '/master/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRolesRoute = MasterRolesRouteImport.update({
  id: '/master/roles',
  path: '/master/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterPoliRoute = MasterPoliRouteImport.update({
  id: '/master/poli',
  path: '/master/poli',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterPasienRoute = MasterPasienRouteImport.update({
  id: '/master/pasien',
  path: '/master/pasien',
  getParentRoute: () => rootRouteImport,
} as any)
const DokterAntreanRoute = DokterAntreanRouteImport.update({
  id: '/dokter/antrean',
  path: '/dokter/antrean',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrasiAntreanRoute = AdministrasiAntreanRouteImport.update({
  id: '/administrasi/antrean',
  path: '/administrasi/antrean',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/administrasi/antrean': typeof AdministrasiAntreanRoute
  '/dokter/antrean': typeof DokterAntreanRoute
  '/master/pasien': typeof MasterPasienRoute
  '/master/poli': typeof MasterPoliRoute
  '/master/roles': typeof MasterRolesRoute
  '/master/users': typeof MasterUsersRoute
  '/pengaturan/faq': typeof PengaturanFaqRoute
  '/pengaturan/jadwal-kontrol': typeof PengaturanJadwalKontrolRoute
  '/pengaturan/konfigurasi-pengingat': typeof PengaturanKonfigurasiPengingatRoute
  '/pengaturan/konfigurasi-sistem': typeof PengaturanKonfigurasiSistemRoute
  '/pengaturan/konfigurasi-whatsapp': typeof PengaturanKonfigurasiWhatsappRoute
  '/pengaturan/template-pesan': typeof PengaturanTemplatePesanRoute
  '/perawat-asisten/antrean': typeof PerawatAsistenAntreanRoute
  '/perawat/antrean': typeof PerawatAntreanRoute
  '/cek-antrean': typeof CekAntreanIndexRoute
  '/display': typeof DisplayIndexRoute
  '/jadwal': typeof JadwalIndexRoute
  '/laporan': typeof LaporanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/administrasi/antrean': typeof AdministrasiAntreanRoute
  '/dokter/antrean': typeof DokterAntreanRoute
  '/master/pasien': typeof MasterPasienRoute
  '/master/poli': typeof MasterPoliRoute
  '/master/roles': typeof MasterRolesRoute
  '/master/users': typeof MasterUsersRoute
  '/pengaturan/faq': typeof PengaturanFaqRoute
  '/pengaturan/jadwal-kontrol': typeof PengaturanJadwalKontrolRoute
  '/pengaturan/konfigurasi-pengingat': typeof PengaturanKonfigurasiPengingatRoute
  '/pengaturan/konfigurasi-sistem': typeof PengaturanKonfigurasiSistemRoute
  '/pengaturan/konfigurasi-whatsapp': typeof PengaturanKonfigurasiWhatsappRoute
  '/pengaturan/template-pesan': typeof PengaturanTemplatePesanRoute
  '/perawat-asisten/antrean': typeof PerawatAsistenAntreanRoute
  '/perawat/antrean': typeof PerawatAntreanRoute
  '/cek-antrean': typeof CekAntreanIndexRoute
  '/display': typeof DisplayIndexRoute
  '/jadwal': typeof JadwalIndexRoute
  '/laporan': typeof LaporanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/no-access': typeof NoAccessRoute
  '/administrasi/antrean': typeof AdministrasiAntreanRoute
  '/dokter/antrean': typeof DokterAntreanRoute
  '/master/pasien': typeof MasterPasienRoute
  '/master/poli': typeof MasterPoliRoute
  '/master/roles': typeof MasterRolesRoute
  '/master/users': typeof MasterUsersRoute
  '/pengaturan/faq': typeof PengaturanFaqRoute
  '/pengaturan/jadwal-kontrol': typeof PengaturanJadwalKontrolRoute
  '/pengaturan/konfigurasi-pengingat': typeof PengaturanKonfigurasiPengingatRoute
  '/pengaturan/konfigurasi-sistem': typeof PengaturanKonfigurasiSistemRoute
  '/pengaturan/konfigurasi-whatsapp': typeof PengaturanKonfigurasiWhatsappRoute
  '/pengaturan/template-pesan': typeof PengaturanTemplatePesanRoute
  '/perawat-asisten/antrean': typeof PerawatAsistenAntreanRoute
  '/perawat/antrean': typeof PerawatAntreanRoute
  '/cek-antrean/': typeof CekAntreanIndexRoute
  '/display/': typeof DisplayIndexRoute
  '/jadwal/': typeof JadwalIndexRoute
  '/laporan/': typeof LaporanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/403'
    | '/login'
    | '/no-access'
    | '/administrasi/antrean'
    | '/dokter/antrean'
    | '/master/pasien'
    | '/master/poli'
    | '/master/roles'
    | '/master/users'
    | '/pengaturan/faq'
    | '/pengaturan/jadwal-kontrol'
    | '/pengaturan/konfigurasi-pengingat'
    | '/pengaturan/konfigurasi-sistem'
    | '/pengaturan/konfigurasi-whatsapp'
    | '/pengaturan/template-pesan'
    | '/perawat-asisten/antrean'
    | '/perawat/antrean'
    | '/cek-antrean'
    | '/display'
    | '/jadwal'
    | '/laporan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/403'
    | '/login'
    | '/no-access'
    | '/administrasi/antrean'
    | '/dokter/antrean'
    | '/master/pasien'
    | '/master/poli'
    | '/master/roles'
    | '/master/users'
    | '/pengaturan/faq'
    | '/pengaturan/jadwal-kontrol'
    | '/pengaturan/konfigurasi-pengingat'
    | '/pengaturan/konfigurasi-sistem'
    | '/pengaturan/konfigurasi-whatsapp'
    | '/pengaturan/template-pesan'
    | '/perawat-asisten/antrean'
    | '/perawat/antrean'
    | '/cek-antrean'
    | '/display'
    | '/jadwal'
    | '/laporan'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/403'
    | '/login'
    | '/no-access'
    | '/administrasi/antrean'
    | '/dokter/antrean'
    | '/master/pasien'
    | '/master/poli'
    | '/master/roles'
    | '/master/users'
    | '/pengaturan/faq'
    | '/pengaturan/jadwal-kontrol'
    | '/pengaturan/konfigurasi-pengingat'
    | '/pengaturan/konfigurasi-sistem'
    | '/pengaturan/konfigurasi-whatsapp'
    | '/pengaturan/template-pesan'
    | '/perawat-asisten/antrean'
    | '/perawat/antrean'
    | '/cek-antrean/'
    | '/display/'
    | '/jadwal/'
    | '/laporan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R403Route: typeof R403Route
  LoginRoute: typeof LoginRoute
  NoAccessRoute: typeof NoAccessRoute
  AdministrasiAntreanRoute: typeof AdministrasiAntreanRoute
  DokterAntreanRoute: typeof DokterAntreanRoute
  MasterPasienRoute: typeof MasterPasienRoute
  MasterPoliRoute: typeof MasterPoliRoute
  MasterRolesRoute: typeof MasterRolesRoute
  MasterUsersRoute: typeof MasterUsersRoute
  PengaturanFaqRoute: typeof PengaturanFaqRoute
  PengaturanJadwalKontrolRoute: typeof PengaturanJadwalKontrolRoute
  PengaturanKonfigurasiPengingatRoute: typeof PengaturanKonfigurasiPengingatRoute
  PengaturanKonfigurasiSistemRoute: typeof PengaturanKonfigurasiSistemRoute
  PengaturanKonfigurasiWhatsappRoute: typeof PengaturanKonfigurasiWhatsappRoute
  PengaturanTemplatePesanRoute: typeof PengaturanTemplatePesanRoute
  PerawatAsistenAntreanRoute: typeof PerawatAsistenAntreanRoute
  PerawatAntreanRoute: typeof PerawatAntreanRoute
  CekAntreanIndexRoute: typeof CekAntreanIndexRoute
  DisplayIndexRoute: typeof DisplayIndexRoute
  JadwalIndexRoute: typeof JadwalIndexRoute
  LaporanIndexRoute: typeof LaporanIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan/': {
      id: '/laporan/'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal/': {
      id: '/jadwal/'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/': {
      id: '/display/'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cek-antrean/': {
      id: '/cek-antrean/'
      path: '/cek-antrean'
      fullPath: '/cek-antrean'
      preLoaderRoute: typeof CekAntreanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perawat/antrean': {
      id: '/perawat/antrean'
      path: '/perawat/antrean'
      fullPath: '/perawat/antrean'
      preLoaderRoute: typeof PerawatAntreanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perawat-asisten/antrean': {
      id: '/perawat-asisten/antrean'
      path: '/perawat-asisten/antrean'
      fullPath: '/perawat-asisten/antrean'
      preLoaderRoute: typeof PerawatAsistenAntreanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/template-pesan': {
      id: '/pengaturan/template-pesan'
      path: '/pengaturan/template-pesan'
      fullPath: '/pengaturan/template-pesan'
      preLoaderRoute: typeof PengaturanTemplatePesanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/konfigurasi-whatsapp': {
      id: '/pengaturan/konfigurasi-whatsapp'
      path: '/pengaturan/konfigurasi-whatsapp'
      fullPath: '/pengaturan/konfigurasi-whatsapp'
      preLoaderRoute: typeof PengaturanKonfigurasiWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/konfigurasi-sistem': {
      id: '/pengaturan/konfigurasi-sistem'
      path: '/pengaturan/konfigurasi-sistem'
      fullPath: '/pengaturan/konfigurasi-sistem'
      preLoaderRoute: typeof PengaturanKonfigurasiSistemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/konfigurasi-pengingat': {
      id: '/pengaturan/konfigurasi-pengingat'
      path: '/pengaturan/konfigurasi-pengingat'
      fullPath: '/pengaturan/konfigurasi-pengingat'
      preLoaderRoute: typeof PengaturanKonfigurasiPengingatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/jadwal-kontrol': {
      id: '/pengaturan/jadwal-kontrol'
      path: '/pengaturan/jadwal-kontrol'
      fullPath: '/pengaturan/jadwal-kontrol'
      preLoaderRoute: typeof PengaturanJadwalKontrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan/faq': {
      id: '/pengaturan/faq'
      path: '/pengaturan/faq'
      fullPath: '/pengaturan/faq'
      preLoaderRoute: typeof PengaturanFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/users': {
      id: '/master/users'
      path: '/master/users'
      fullPath: '/master/users'
      preLoaderRoute: typeof MasterUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/roles': {
      id: '/master/roles'
      path: '/master/roles'
      fullPath: '/master/roles'
      preLoaderRoute: typeof MasterRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/poli': {
      id: '/master/poli'
      path: '/master/poli'
      fullPath: '/master/poli'
      preLoaderRoute: typeof MasterPoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/pasien': {
      id: '/master/pasien'
      path: '/master/pasien'
      fullPath: '/master/pasien'
      preLoaderRoute: typeof MasterPasienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokter/antrean': {
      id: '/dokter/antrean'
      path: '/dokter/antrean'
      fullPath: '/dokter/antrean'
      preLoaderRoute: typeof DokterAntreanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrasi/antrean': {
      id: '/administrasi/antrean'
      path: '/administrasi/antrean'
      fullPath: '/administrasi/antrean'
      preLoaderRoute: typeof AdministrasiAntreanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R403Route: R403Route,
  LoginRoute: LoginRoute,
  NoAccessRoute: NoAccessRoute,
  AdministrasiAntreanRoute: AdministrasiAntreanRoute,
  DokterAntreanRoute: DokterAntreanRoute,
  MasterPasienRoute: MasterPasienRoute,
  MasterPoliRoute: MasterPoliRoute,
  MasterRolesRoute: MasterRolesRoute,
  MasterUsersRoute: MasterUsersRoute,
  PengaturanFaqRoute: PengaturanFaqRoute,
  PengaturanJadwalKontrolRoute: PengaturanJadwalKontrolRoute,
  PengaturanKonfigurasiPengingatRoute: PengaturanKonfigurasiPengingatRoute,
  PengaturanKonfigurasiSistemRoute: PengaturanKonfigurasiSistemRoute,
  PengaturanKonfigurasiWhatsappRoute: PengaturanKonfigurasiWhatsappRoute,
  PengaturanTemplatePesanRoute: PengaturanTemplatePesanRoute,
  PerawatAsistenAntreanRoute: PerawatAsistenAntreanRoute,
  PerawatAntreanRoute: PerawatAntreanRoute,
  CekAntreanIndexRoute: CekAntreanIndexRoute,
  DisplayIndexRoute: DisplayIndexRoute,
  JadwalIndexRoute: JadwalIndexRoute,
  LaporanIndexRoute: LaporanIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
