/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JadwalIndexRouteImport } from './routes/jadwal/index'
import { Route as DisplayIndexRouteImport } from './routes/display/index'
import { Route as AntreanIndexRouteImport } from './routes/antrean/index'
import { Route as ResepsionisAntreanRouteImport } from './routes/resepsionis/antrean'
import { Route as PerawatAntreanRouteImport } from './routes/perawat/antrean'
import { Route as MasterUsersRouteImport } from './routes/master/users'
import { Route as MasterRolesRouteImport } from './routes/master/roles'
import { Route as MasterPoliRouteImport } from './routes/master/poli'
import { Route as DokterAntreanRouteImport } from './routes/dokter/antrean'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JadwalIndexRoute = JadwalIndexRouteImport.update({
  id: '/jadwal/',
  path: '/jadwal/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayIndexRoute = DisplayIndexRouteImport.update({
  id: '/display/',
  path: '/display/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntreanIndexRoute = AntreanIndexRouteImport.update({
  id: '/antrean/',
  path: '/antrean/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResepsionisAntreanRoute = ResepsionisAntreanRouteImport.update({
  id: '/resepsionis/antrean',
  path: '/resepsionis/antrean',
  getParentRoute: () => rootRouteImport,
} as any)
const PerawatAntreanRoute = PerawatAntreanRouteImport.update({
  id: '/perawat/antrean',
  path: '/perawat/antrean',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterUsersRoute = MasterUsersRouteImport.update({
  id: '/master/users',
  path: '/master/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRolesRoute = MasterRolesRouteImport.update({
  id: '/master/roles',
  path: '/master/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterPoliRoute = MasterPoliRouteImport.update({
  id: '/master/poli',
  path: '/master/poli',
  getParentRoute: () => rootRouteImport,
} as any)
const DokterAntreanRoute = DokterAntreanRouteImport.update({
  id: '/dokter/antrean',
  path: '/dokter/antrean',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/dokter/antrean': typeof DokterAntreanRoute
  '/master/poli': typeof MasterPoliRoute
  '/master/roles': typeof MasterRolesRoute
  '/master/users': typeof MasterUsersRoute
  '/perawat/antrean': typeof PerawatAntreanRoute
  '/resepsionis/antrean': typeof ResepsionisAntreanRoute
  '/antrean': typeof AntreanIndexRoute
  '/display': typeof DisplayIndexRoute
  '/jadwal': typeof JadwalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/dokter/antrean': typeof DokterAntreanRoute
  '/master/poli': typeof MasterPoliRoute
  '/master/roles': typeof MasterRolesRoute
  '/master/users': typeof MasterUsersRoute
  '/perawat/antrean': typeof PerawatAntreanRoute
  '/resepsionis/antrean': typeof ResepsionisAntreanRoute
  '/antrean': typeof AntreanIndexRoute
  '/display': typeof DisplayIndexRoute
  '/jadwal': typeof JadwalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/dokter/antrean': typeof DokterAntreanRoute
  '/master/poli': typeof MasterPoliRoute
  '/master/roles': typeof MasterRolesRoute
  '/master/users': typeof MasterUsersRoute
  '/perawat/antrean': typeof PerawatAntreanRoute
  '/resepsionis/antrean': typeof ResepsionisAntreanRoute
  '/antrean/': typeof AntreanIndexRoute
  '/display/': typeof DisplayIndexRoute
  '/jadwal/': typeof JadwalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/dokter/antrean'
    | '/master/poli'
    | '/master/roles'
    | '/master/users'
    | '/perawat/antrean'
    | '/resepsionis/antrean'
    | '/antrean'
    | '/display'
    | '/jadwal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/dokter/antrean'
    | '/master/poli'
    | '/master/roles'
    | '/master/users'
    | '/perawat/antrean'
    | '/resepsionis/antrean'
    | '/antrean'
    | '/display'
    | '/jadwal'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/login'
    | '/dokter/antrean'
    | '/master/poli'
    | '/master/roles'
    | '/master/users'
    | '/perawat/antrean'
    | '/resepsionis/antrean'
    | '/antrean/'
    | '/display/'
    | '/jadwal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LoginRoute: typeof LoginRoute
  DokterAntreanRoute: typeof DokterAntreanRoute
  MasterPoliRoute: typeof MasterPoliRoute
  MasterRolesRoute: typeof MasterRolesRoute
  MasterUsersRoute: typeof MasterUsersRoute
  PerawatAntreanRoute: typeof PerawatAntreanRoute
  ResepsionisAntreanRoute: typeof ResepsionisAntreanRoute
  AntreanIndexRoute: typeof AntreanIndexRoute
  DisplayIndexRoute: typeof DisplayIndexRoute
  JadwalIndexRoute: typeof JadwalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jadwal/': {
      id: '/jadwal/'
      path: '/jadwal'
      fullPath: '/jadwal'
      preLoaderRoute: typeof JadwalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/': {
      id: '/display/'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/antrean/': {
      id: '/antrean/'
      path: '/antrean'
      fullPath: '/antrean'
      preLoaderRoute: typeof AntreanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resepsionis/antrean': {
      id: '/resepsionis/antrean'
      path: '/resepsionis/antrean'
      fullPath: '/resepsionis/antrean'
      preLoaderRoute: typeof ResepsionisAntreanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perawat/antrean': {
      id: '/perawat/antrean'
      path: '/perawat/antrean'
      fullPath: '/perawat/antrean'
      preLoaderRoute: typeof PerawatAntreanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/users': {
      id: '/master/users'
      path: '/master/users'
      fullPath: '/master/users'
      preLoaderRoute: typeof MasterUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/roles': {
      id: '/master/roles'
      path: '/master/roles'
      fullPath: '/master/roles'
      preLoaderRoute: typeof MasterRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master/poli': {
      id: '/master/poli'
      path: '/master/poli'
      fullPath: '/master/poli'
      preLoaderRoute: typeof MasterPoliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokter/antrean': {
      id: '/dokter/antrean'
      path: '/dokter/antrean'
      fullPath: '/dokter/antrean'
      preLoaderRoute: typeof DokterAntreanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LoginRoute: LoginRoute,
  DokterAntreanRoute: DokterAntreanRoute,
  MasterPoliRoute: MasterPoliRoute,
  MasterRolesRoute: MasterRolesRoute,
  MasterUsersRoute: MasterUsersRoute,
  PerawatAntreanRoute: PerawatAntreanRoute,
  ResepsionisAntreanRoute: ResepsionisAntreanRoute,
  AntreanIndexRoute: AntreanIndexRoute,
  DisplayIndexRoute: DisplayIndexRoute,
  JadwalIndexRoute: JadwalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
